apiVersion: apps/v1
kind: Deployment
metadata:
  name: mluft-dos
  labels:
    app: mluft-dos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mluft-dos
  template:
    metadata:
      labels:
        app: mluft-dos
    spec:
      containers:
      - image: uchimata/dos
        imagePullPolicy: Always
        name: dos
        # Argument defines sleep time after allocating memory in s
        command: ["/app/fill-memory.sh", "5"] 
        #command: ["/app/fill-disk.sh"] 
        #command: ["/app/forkbomb.sh"] 
